#!/bin/bash

LOG=/boot/config/plugins/user.scripts/scripts/clearerr/clearerr.log

log_trace() {
    echo "$(date '+%Y-%m-%d %H:%M:%S') [TRACE] (bash) $1" >> "$LOG"
}

log_trace "Entering cleararr python program"

source /boot/config/plugins/user.scripts/scripts/clearerr/.env

python3 /boot/config/plugins/user.scripts/scripts/clearerr/clearerr.py >> "$LOG" 2>&1

log_trace "Exited cleararr python program"